# Generated by Django 4.2.24 on 2025-10-01 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Район',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Слой',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapapi.category')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapapi.district')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapapi.layer')),
            ],
            options={
                'verbose_name': 'Объект',
            },
        ),
        migrations.CreateModel(
            name='LayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('score_10', models.DecimalField(decimal_places=2, max_digits=5)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_scores', to='mapapi.district')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mapapi.layer')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('summary_10', models.DecimalField(decimal_places=2, max_digits=5)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='mapapi.district')),
            ],
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['slug'], name='mapapi_dist_slug_023cee_idx'),
        ),
        migrations.AddField(
            model_name='category',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='mapapi.layer'),
        ),
    ]
