# Generated by Django 4.2.24 on 2025-12-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='geom',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['district'], name='mapapi_obje_distric_63da18_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['category'], name='mapapi_obje_categor_f4c581_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['layer'], name='mapapi_obje_layer_i_6b4c09_idx'),
        ),
    ]
