# Generated by Django 4.2.24 on 2025-12-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0002_object_geom_object_lat_object_lon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoDistrictStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yards', models.IntegerField(default=0)),
                ('parks', models.IntegerField(default=0)),
                ('hazards_count', models.IntegerField(default=0)),
                ('green_index', models.FloatField(default=0.0)),
                ('hazard_index', models.FloatField(default=0.0)),
                ('hazard_safe_index', models.FloatField(default=0.0)),
                ('eco_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eco статистика района',
            },
        ),
        migrations.RemoveIndex(
            model_name='object',
            name='mapapi_obje_distric_63da18_idx',
        ),
        migrations.RemoveIndex(
            model_name='object',
            name='mapapi_obje_categor_f4c581_idx',
        ),
        migrations.RemoveIndex(
            model_name='object',
            name='mapapi_obje_layer_i_6b4c09_idx',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='geom',
            new_name='geometry',
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='districtrating',
            index=models.Index(fields=['district'], name='mapapi_dist_distric_f00c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='layerscore',
            index=models.Index(fields=['district', 'layer'], name='mapapi_laye_distric_1ff38a_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['district', 'layer', 'category'], name='mapapi_obje_distric_cd28f5_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['layer', 'category'], name='mapapi_obje_layer_i_484204_idx'),
        ),
        migrations.AddField(
            model_name='ecodistrictstats',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eco_stats', to='mapapi.district'),
        ),
    ]
