# Generated by Django 4.2.24 on 2026-01-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0003_ecodistrictstats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecodistrictstats',
            old_name='yards',
            new_name='forests',
        ),
    ]
