# Generated by Django 4.2.24 on 2026-02-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0004_rename_yards_ecodistrictstats_forests'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDistrictStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('culture', models.IntegerField(default=0)),
                ('sport', models.IntegerField(default=0)),
                ('commerce', models.IntegerField(default=0)),
                ('social_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_stats', to='mapapi.district')),
            ],
            options={
                'verbose_name': 'Social статистика района',
            },
        ),
    ]
