# Generated by Django 4.2.24 on 2026-03-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0005_socialdistrictstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
