# Generated by Django 4.2.24 on 2026-04-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0006_object_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseDistrictStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurements_count', models.IntegerField(default=0)),
                ('avg_noise_db', models.FloatField(default=0.0)),
                ('max_noise_db', models.FloatField(default=0.0)),
                ('noise_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noise_stats', to='mapapi.district')),
            ],
            options={
                'verbose_name': 'Noise статистика района',
            },
        ),
    ]
