# Generated by Django 4.2.24 on 2026-04-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapi', '0007_noisedistrictstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noisedistrictstats',
            old_name='measurements_count',
            new_name='construction_count',
        ),
        migrations.RemoveField(
            model_name='noisedistrictstats',
            name='avg_noise_db',
        ),
        migrations.RemoveField(
            model_name='noisedistrictstats',
            name='max_noise_db',
        ),
        migrations.AddField(
            model_name='noisedistrictstats',
            name='loading_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noisedistrictstats',
            name='other_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noisedistrictstats',
            name='road_repair_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noisedistrictstats',
            name='total_complaints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noisedistrictstats',
            name='ventilation_count',
            field=models.IntegerField(default=0),
        ),
    ]
